# Generated by Django 6.1 on 2026-08-31 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessibility', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_accessibilities', to='acessibility.accessibilitycharacteristic')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibilities', to='places.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='characteristics',
            field=models.ManyToManyField(related_name='places', through='places.PlaceAccessibility', to='acessibility.accessibilitycharacteristic'),
        ),
        migrations.AddConstraint(
            model_name='placeaccessibility',
            constraint=models.UniqueConstraint(fields=('place', 'characteristic'), name='unique_characteristic_per_place'),
        ),
    ]
