# Generated by Django 6.1 on 2026-08-31 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessibility', '0002_accessibilitylevel_and_more'),
        ('places', '0002_placeaccessibility_place_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeaccessibility',
            name='value',
        ),
        migrations.AddField(
            model_name='placeaccessibility',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeaccessibility',
            name='value_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='place_accessibilities', to='acessibility.accessibilitylevel'),
        ),
        migrations.AddField(
            model_name='placeaccessibility',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='placeaccessibility',
            name='value_text',
            field=models.TextField(blank=True),
        ),
    ]
