# Generated by Django 6.1 on 2026-08-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessibility', '0002_accessibilitylevel_and_more'),
        ('places', '0003_remove_placeaccessibility_value_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeaccessibility',
            index=models.Index(fields=['place'], name='place_access_place_idx'),
        ),
        migrations.AddIndex(
            model_name='placeaccessibility',
            index=models.Index(fields=['characteristic'], name='place_access_char_idx'),
        ),
    ]
