# Generated by Django 6.1 on 2026-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeaccessibility_place_access_place_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
