# Generated by Django 6.1 on 2026-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_google_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='google_place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
