# Generated by Django 6.1 on 2026-09-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_google_place_id_remove_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='high_movement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='strong_lights',
            field=models.BooleanField(default=False),
        ),
    ]
