# Generated by Django 6.1 on 2026-08-31 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_review_place_idx_review_review_user_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='review_place_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='review_user_idx',
        ),
    ]
