# Generated by Django 6.1 on 2026-08-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sensory_sensibility',
            new_name='sensory_sensitivity',
        ),
    ]
