# Generated by Django 6.1 on 2026-08-31 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de acessibilidade',
                'verbose_name_plural': 'Categorias de acessibilidade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characteristics', to='acessibility.accessibilitycategory')),
            ],
            options={
                'verbose_name': 'Característica de acessibilidade',
                'verbose_name_plural': 'Características de acessibilidade',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_characteristic_per_category')],
            },
        ),
    ]
