# Generated by Django 6.1 on 2026-08-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nível de acessibilidade',
                'verbose_name_plural': 'Níveis de acessibilidade',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='accessibilitycharacteristic',
            name='value_type',
            field=models.CharField(choices=[('BOOLEAN', 'Sim/Não'), ('LEVEL', 'Nível'), ('TEXT', 'Texto'), ('NUMBER', 'Número')], default='TEXT', max_length=20),
        ),
    ]
